name: Run Bash Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cloning git
        run: |
          git config user.name "asauliya"
          git config user.email "ishusjn@gmail.com"
          npx create-react-app myApp
          cd myApp
      - name: Run Bash script
        run: |
          chmod +x ./script.sh
          ./script.sh
      - name: Git commit changes
        run: |
          git add .
          git commit -m "NO COMMENT"
          git push -u origin main
